#!/usr/bin/env node
// Places: merge the currency-checked parts into the typed data file the surface renders.
// Source of truth for what is on the page = scripts/places/checked/part-*.json (evidence-bearing);
// src/data/places.ts is GENERATED — edit the JSON, re-run this, never hand-edit the .ts.
// Usage: node scripts/places/merge.mjs
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const checkedDir = join(here, 'checked');
const out = join(here, '..', '..', 'src', 'data', 'places.ts');

const REGIONS = ['london','south-east','south-west','midlands','north','wales','scotland','uk-wide'];
const KINDS = ['organisation','group','venue','club-night','collective','service','network'];
const CENTRES = ['black-queer-men','black-lgbtq','qtipoc','lgbtq-broad','general'];
const STATUSES = ['live','unclear','dormant','closed'];

// Rob's rulings outrank any checker. Anything in never-list.json is dropped before it can be published.
const never = JSON.parse(readFileSync(join(here, 'never-list.json'), 'utf8')).never;
const isNever = (p) => never.some((n) => n.id === p.id || (p.name ?? '').toLowerCase().includes(n.match));

const parts = readdirSync(checkedDir).filter((f) => /^part-\d+\.json$/.test(f)).sort();
if (parts.length === 0) { console.error('NO-REPORT: no checked/part-*.json found'); process.exit(1); }

const PLACE_KEYS = ['id','name','what','where','region','kind','regular','url','instagram','centres','checked','evidence','excludesMen','status','borough'];
const norm = (n) => n.toLowerCase().replace(/\(.*?\)/g, '').replace(/[^a-z0-9]/g, '');
const seen = new Map();
const byName = new Map();
const problems = [];
for (const f of parts) {
  const arr = JSON.parse(readFileSync(join(checkedDir, f), 'utf8'));
  for (const p of arr) {
    const where = `${f}:${p.id ?? p.name}`;
    if (!p.id || !p.name) problems.push(`${where}: missing id/name`);
    if (p.status === 'live' && (!p.what || !p.where)) problems.push(`${where}: live entry missing what/where`);
    if (!REGIONS.includes(p.region)) problems.push(`${where}: bad region ${p.region}`);
    if (!KINDS.includes(p.kind)) problems.push(`${where}: bad kind ${p.kind}`);
    if (!CENTRES.includes(p.centres)) problems.push(`${where}: bad centres ${p.centres}`);
    if (!STATUSES.includes(p.status)) problems.push(`${where}: bad status ${p.status}`);
    if (!p.evidence) problems.push(`${where}: no evidence line`);
    if (p.status === 'live' && !/20\d\d|jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec/i.test(p.evidence ?? ''))
      problems.push(`${where}: status live but evidence carries no date`);
    if (seen.has(p.id)) console.log(`id-dedupe: ${p.id} superseded by ${f}`);
    if (isNever(p)) { console.log(`never-list: dropped ${p.id}`); continue; }
    const clean = Object.fromEntries(PLACE_KEYS.filter((k) => p[k] !== undefined).map((k) => [k, p[k]]));
    const nk = norm(p.name);
    if (byName.has(nk)) { const prev = byName.get(nk); console.log(`name-dedupe: ${prev} superseded by ${p.id} (${f})`); seen.delete(prev); }
    byName.set(nk, p.id);
    seen.set(p.id, clean);
  }
}
if (problems.length) { console.error('FAILED — fix the JSON:\n' + problems.join('\n')); process.exit(1); }

const places = [...seen.values()].sort((a, b) =>
  REGIONS.indexOf(a.region) - REGIONS.indexOf(b.region) || a.name.localeCompare(b.name));

const published = places.filter((p) => p.status === 'live' && !p.excludesMen && ['black-queer-men','black-lgbtq','qtipoc'].includes(p.centres));

const doorSlugs = readdirSync(join(here, '..', 'borough-doors', 'data')).filter((f) => /^[a-z-]+\.json$/.test(f)).map((f) => f.replace('.json', ''));

const ts = `// GENERATED by scripts/places/merge.mjs from scripts/places/checked/part-*.json — do not hand-edit.
// ${places.length} entries checked ${[...new Set(places.map((p) => p.checked))].join(', ')}; ${published.length} pass the publish rule.
import type { Place } from '../types/surface';

export const places: Place[] = ${JSON.stringify(places, null, 2)};

/** The publish rule (spec §2 + 28 Aug): dated activity inside 12 months, centres Black queer people, and does not state an audience that excludes men. */
export const publishedPlaces = (): Place[] =>
  places.filter((p) => p.status === 'live' && !p.excludesMen && ['black-queer-men', 'black-lgbtq', 'qtipoc'].includes(p.centres));

/** Borough doors that exist today (from scripts/borough-doors/data) — a Place with a matching borough links to its door. */
export const doorSlugs: string[] = ${JSON.stringify(doorSlugs)};
export const boroughSlug = (b: string): string => b.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

/** Entries in the file that are not shown — the Note reports this count. */
export const heldPlacesCount = (): number => places.length - publishedPlaces().length;
`;
writeFileSync(out, ts);
// The same data for the borough-door generator (plain JSON, published flag included).
writeFileSync(join(here, 'places.json'), JSON.stringify(places.map((p) => ({ ...p, published: published.includes(p) })), null, 2));
const byStatus = Object.fromEntries(STATUSES.map((s) => [s, places.filter((p) => p.status === s).length]));
console.log(`wrote ${out}: ${places.length} entries, ${published.length} published`, byStatus);
